### ISSUE TITLE
Plugin not working on OJS 3.2.0.1

### ISSUE THREAD

**Issue by alexxxmendonca** [publons/ojs_3_plugin#3]
We updated the SciELO OJS to version 3.2.0.1 and the Publons plugin hasn't been working since.

We had the plugin installed in several journals but after the upgrade, the plugin disappeared from all journals. We assume it has stopped working since then (given that it's not listed on the list of installed plugins).

We manually installed the plugin again in a sample journal and when we click on the "Connection" link, it gives the following error:

![image](https://user-images.githubusercontent.com/4059679/80020961-38c88f80-84b0-11ea-99bf-ca9937813e57.png)

**Comment by broc-harcourt** [comment]
Thanks for reporting @Alex-nz. My understanding is that v3.2 of OJS contained many breaking changes (https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.2-release-notebook) and we have not yet brought out plugin up to speed with these. Thus though we haven't investigated yet I expect that it is the version upgrade that has caused this problem.

I'll update this this issue once we confirm that it is v3.2 incompatibility that has caused this, and also once we have a timeline on implementing compatibility. Apologies that leaves you in a poor spot currently.

**Comment by Alex-nz** [comment]
I think you were meant to mention @alexxxmendonca here Broc

**Comment by alexxxmendonca** [comment]
Thank you @broc-harcourt 

Our main concern is that we might have to manually re-enter again all credentials, journal by journal.

**Comment by broc-harcourt** [comment]
> Our main concern is that we might have to manually re-enter again all credentials

Ok. We're looking at this with some urgency and will keep this (highly undesirable) outcome in mind. Do let me know if you encounter further specific issues.

**Comment by broc-harcourt** [comment]
Sorry for the significant delay on this @alexxxmendonca. We just made a release which is compatible with OJS v3.2.0:
https://github.com/publons/ojs_3_plugin/releases/tag/v2020.06.05

Note that this release is not listed in the OJS plugin gallery yet but the `.tar.gz` file can be taken directly from that release link. We are following up on getting the release into the plugin gallery as well as some other tidy ups.

**Comment by alexxxmendonca** [comment]
Hello @broc-harcourt 

When I try to upgrade it, I get the following error message:

![image](https://user-images.githubusercontent.com/4059679/83871803-1c528080-a707-11ea-84e6-c0dffbb66bc8.png)

What I did was:

1) Downloaded **Source code (tar.gz)** from https://github.com/publons/ojs_3_plugin/releases/tag/v2020.06.05
2) Uploaded the file

Am I doing anything wrong?

**Comment by broc-harcourt** [comment]
Sorry for the further problems @alexxxmendonca. We're looking at this and will update you as soon as we can.

**Comment by broc-harcourt** [comment]
Hi @alexxxmendonca. We've adjusted that release today (https://github.com/publons/ojs_3_plugin/releases/tag/v2020.06.05), please try again but this time use the newly added [publons.tar.gz](https://github.com/publons/ojs_3_plugin/releases/download/v2020.06.05/publons.tar.gz) rather than the "source code" .tar.gz file.

**Comment by alexxxmendonca** [comment]
Hi @broc-harcourt 

Yes, it worked now! Thanks! Thankfully we didn't lose all the credentials.
