### ISSUE TITLE
Restructure for git deployments

### ISSUE THREAD

**Issue by ctgraham** [publons/ojs_3_plugin#5]
Can this plugin be restructured to move the contents in the "publons" folder directly into the root of the repository?  This will align better with the structure of other PKP plugin repositories, and allow for direct inclusion of the repository as a git submodule, e.g.:
```
git submodule add https://github.com/publons/ojs_3_plugin.git plugins/generic/publons
```

This also may simplify the build of the .tgz for release and will package the readme in the release.

**Comment by ctgraham** [comment]
@broc-harcourt, can you comment on concerns or plans here?

**Comment by broc-harcourt** [comment]
Hi @ctgraham. Thanks for the pointer. We're making these changes at the moment. Sorry there has been some delay.

**Comment by broc-harcourt** [comment]
Changes made. Files have been shifted into the parent directory.

Some care needs to be taken as the folder name should be `publons`, which is not the repository name.

Thanks for the suggestion @ctgraham.
