### ISSUE TITLE
Problem using plugin on OJS 3.2.0.3

### ISSUE THREAD

**Issue by edersotto** [publons/ojs_3_plugin#7]
Hi, I had trouble to configure and sending a review to publons. I am using the latest version of the plugin (2020.6.5.0). The reported error was "Error exporting to Publons". The PHP error log contains "PHP Notice: Undefined index: HTTP_PUBLONS_URL in /var/www/revistamosaicum/plugins/generic/publons/PublonsHandler.inc.php on line 189, referer: https://revistamosaicum.org/index. php / mosaicum / reviewer / submission / 93 ". My OJS Version in OJS 3.2.0.3. Can you help me? Thank you!

![error](https://user-images.githubusercontent.com/19962752/85715692-1a565e80-b6c2-11ea-8bd5-ce787adcb43b.png)

![image](https://user-images.githubusercontent.com/19962752/85717594-0e6b9c00-b6c4-11ea-93dc-e5d65f12fcfb.png)

![image](https://user-images.githubusercontent.com/19962752/85717766-3a871d00-b6c4-11ea-862d-861596e78f77.png)

It is the complete error log:

![image](https://user-images.githubusercontent.com/19962752/85768696-ab8ffa00-b6ef-11ea-845a-8da59bd63bac.png)

**Comment by broc-harcourt** [comment]
Hi @edersotto,

I'm very sorry for the slow response here.

This plugin is intended to integrate with Publons Reviewer Recognition Service, which is a paid for service. If you're interested in finding out more about this or requesting a quote please see https://publons.com/benefits/publishers/reviewer-recognition and we can go from there.

Thanks for your interest, and apologies again for the delayed reply.
