### ISSUE TITLE
Any plans to update this plugin for OJS 3.2?

### ISSUE THREAD

**Issue by NateWr** [publons/ojs_3_plugin#9]
I notice that this plugin is [compatible with OJS 3.1.x](https://github.com/pkp/plugin-gallery/blob/master/plugins.xml#L3067-L3081) but is not yet compatible with OJS 3.2 or later. Do you have any plans to update this plugin for 3.2?

The docs include information on [releasing updates](https://docs.pkp.sfu.ca/dev/plugin-guide/en/release) as well as writing tests so that you can test compatibility more easily.

**Comment by broc-harcourt** [comment]
Hi @NateWr,

**Comment by NateWr** [comment]
Thanks @broc-harcourt, that's great to hear!
